logger:
  level: 0
  encoding: "console"
  output:
    - "stdout"
    - "logger_logs.log"
server:
  host: "localhost"
  port: 8080
database:
  implementation: "sql"
  username: "postgres"
  password: "postgres"
  name: "calendar"
  host: "localhost"
  port: 5432
  ssl_mode: "disable"